### ISSUE TITLE
I've created a HomeBridge plugin based on the "idasen-controller".

### ISSUE THREAD

**Issue by vniehues** [Pob4acke/homebridge_idasen#1]
Hey @Pob4acke 

After I googled for hours I finally found your mention of this repo in a German apple forum.
I started using your way and thought I should be able to create this in Typescript. 
I took the idea of simply executing the idasen-controller command (instead of implementing it myself) from you. 

There is no real readme for now but I'll make sure to credit you. 
Here is a link to the repo:
[https://github.com/vniehues/linak-homebridge](https://github.com/vniehues/linak-homebridge)

I thought I'd let you know that the last point on your ToDo list is done :) 

Thanks again for the inspiration to just call the existing implementation from my code. 

Cheers from a fellow German dev :)

**Comment by Pob4acke** [comment]
Hi @vniehues,

nice! I did hope someone would do any better than me, but was never expecting to have a proper solution that fast.
I will test it out, as a proper plugin is definitely better than my quick and dirty workaround ;)

If I get into the Homebridge development in general a bit, I try to contribute to yours then.

**Comment by vniehues** [comment]
Any contributions are always welcome! :) 
Feel free to reach out to me when you have any questions. Also I can recommend the Homebridge Discord if you have any questions regarding plugin development - I'm certainly not as qualified as some of the other members there.
